#!/usr/bin/env bash
#
# preflight-storage.sh - verify that the hostPath volumes bind and are writable.
#
# Run this AFTER `kubectl apply -f base/` on the target cluster:
#
#   ./infrastructure/kubernetes/scripts/preflight-storage.sh
#
# Why this is a check and not a "create the directories" script:
#   storage-volumes.yaml uses `hostPath.type: DirectoryOrCreate`, so kubelet
#   creates the missing directories itself. The only thing left to get wrong is
#   ownership, and the init containers (init-data-dir / init-mongo-data) fix that
#   at pod start. This script proves both facts instead of assuming them.
#
# It is read-only against the cluster: it never creates, patches or deletes a
# resource. Exit code 0 = all bound, non-zero = see the report.
set -euo pipefail

NAMESPACE="${NAMESPACE:-default}"
TIMEOUT="${TIMEOUT:-120}"

# PV name -> hostPath directory. Keep in sync with base/storage-volumes.yaml.
declare -A PV_PATHS=(
  [postgres-auth-pv]="/mnt/data/postgres-auth"
  [mongodb-orders-pv]="/mnt/data/mongodb-orders"
)

red()   { printf '\033[31m%s\033[0m\n' "$*"; }
green() { printf '\033[32m%s\033[0m\n' "$*"; }
yellow(){ printf '\033[33m%s\033[0m\n' "$*"; }

fail=0

echo "==> cluster connectivity"
if ! kubectl cluster-info >/dev/null 2>&1; then
  red "FAIL: cannot reach the cluster. Check your kubeconfig / current-context."
  exit 2
fi
current_ctx="$(kubectl config current-context 2>/dev/null || echo '<none>')"
echo "    context: $current_ctx"
echo "    namespace: $NAMESPACE"

echo
echo "==> storage class 'manual'"
if kubectl get storageclass manual >/dev/null 2>&1; then
  sc="$(kubectl get storageclass manual -o jsonpath='{.provisioner}')"
  vm="$(kubectl get storageclass manual -o jsonpath='{.volumeBindingMode}')"
  green "    found (provisioner=$sc, bindingMode=${vm:-Immediate})"
else
  yellow "    WARN: storageclass 'manual' missing - the StatefulSet PVCs will stay Pending"
  fail=1
fi

echo
echo "==> persistent volumes"
for pv in "${!PV_PATHS[@]}"; do
  path="${PV_PATHS[$pv]}"
  if ! kubectl get pv "$pv" >/dev/null 2>&1; then
    red "    $pv: NOT FOUND in the cluster"
    fail=1
    continue
  fi

  status="$(kubectl get pv "$pv" -o jsonpath='{.status.phase}')"
  claim="$(kubectl get pv "$pv" -o jsonpath='{.spec.claimRef.name}')"
  [ -z "$claim" ] && claim="<unbound>"

  case "$status" in
    Bound)   green "    $pv: $status -> $claim" ;;
    Pending) yellow "    $pv: $status -> $claim  (expected until a pod is scheduled:
                   volumeBindingMode=WaitForFirstConsumer defers binding)" ;;
    *)       red "    $pv: $status"; fail=1 ;;
  esac
  echo "      hostPath: $path"
done

echo
echo "==> claims"
# The auth-postgres claim is generated by the StatefulSet, so it only exists
# once that StatefulSet has been created.
for claim in data-auth-postgres-0 mongodb-orders-pvc; do
  if kubectl -n "$NAMESPACE" get pvc "$claim" >/dev/null 2>&1; then
    phase="$(kubectl -n "$NAMESPACE" get pvc "$claim" -o jsonpath='{.status.phase}')"
    vol="$(kubectl -n "$NAMESPACE" get pvc "$claim" -o jsonpath='{.spec.volumeName}')"
    case "$phase" in
      Bound)   green "    $claim: $phase ($vol)" ;;
      Pending) yellow "    $claim: Pending -> ${vol:-<no volume yet>}" ;;
      *)       red "    $claim: $phase"; fail=1 ;;
    esac
  else
    yellow "    $claim: not created yet"
  fi
done

echo
echo "==> pod ownership of the data directory"
# Confirms the init containers actually ran and chowned the mount.
#
# The reason is read from `state.terminated.reason`, NOT from `state`.
# `state` alone renders as a Go map
# (map[terminated:map[exitCode:0 reason:Completed ...]]), so comparing it to
# the string "terminated" is never true: the branch below silently never ran
# and the ownership stat - the entire point of this check - was never made.
check_init() {
  local sel="$1" cname="$2" container="$3" path="$4"

  if ! kubectl -n "$NAMESPACE" get pod -l "app=$sel" >/dev/null 2>&1; then
    yellow "    $sel pod not created yet"
    return
  fi

  local pod
  pod="$(kubectl -n "$NAMESPACE" get pod -l "app=$sel" -o jsonpath='{.items[0].metadata.name}')"

  local reason
  reason="$(kubectl -n "$NAMESPACE" get pod "$pod" \
              -o jsonpath="{.status.initContainerStatuses[?(@.name==\"$cname\")].state.terminated.reason}")"
  if [ "$reason" != "Completed" ]; then
    yellow "    $cname on $pod: ${reason:-not completed yet}"
    return
  fi
  green "    $cname on $pod: completed"

  local owner
  owner="$(kubectl -n "$NAMESPACE" exec "$pod" -c "$container" \
             -- stat -c '%u:%g %a' "$path" 2>/dev/null || echo '?')"
  case "$owner" in
    999:999*) green "    $path owned by $owner" ;;
    *)        yellow "    WARN: $path owned by $owner (expected 999:999)" ;;
  esac
}

# Postgres (StatefulSet) and MongoDB (own Deployment since the infra-db pod
# was split) both chown a hostPath mount to uid 999, so both are verified.
check_init auth-postgres init-data-dir  postgres       /var/lib/postgresql/data
check_init order-mongodb  init-mongo-data order-mongodb /data/db

echo
if [ "$fail" -eq 0 ]; then
  green "PREFLIGHT OK - volumes bound and owned by the service user"
  exit 0
fi
red "PREFLIGHT FAILED - see the red lines above"
exit 1
