apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: payment-service:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8085
          env:
            - name: RABBITMQ_URL
              value: "amqp://admin:ProdRabbitBrokerPass2026Secure99@message-rabbitmq-service:5672"
