apiVersion: apps/v1
kind: Deployment
metadata:
  name: infrastructure-databases
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infra-db
  template:
    metadata:
      labels:
        app: infra-db
    spec:
      containers:
        # 1. Redis для Корзины (Node.js)
        - name: cart-redis
          image: redis:7.0-alpine
          ports:
            - containerPort: 6379
              name: redis-port
              
        # 2. MongoDB для Заказов (.NET 8)
        - name: order-mongodb
          image: mongo:6.0
          ports:
            - containerPort: 27017
              name: mongo-port

        # 3. RabbitMQ Брокер для Асинхронного Pub/Sub контура
        - name: message-rabbitmq
          image: rabbitmq:3.12-management-alpine
          ports:
            - containerPort: 5672
              name: amqp-port
            - containerPort: 15672
              name: amqp-mgmt
---
apiVersion: v1
kind: Service
metadata:
  name: cart-redis-service
spec:
  ports:
    - port: 6379
      targetPort: redis-port
  selector:
    app: infra-db
---
apiVersion: v1
kind: Service
metadata:
  name: order-mongodb-service
spec:
  ports:
    - port: 27017
      targetPort: mongo-port
  selector:
    app: infra-db
---
apiVersion: v1
kind: Service
metadata:
  name: message-rabbitmq-service
spec:
  ports:
    - port: 5672
      targetPort: amqp-port
  selector:
    app: infra-db
