replicaCount: 1
image:
  repository: myregistry/catalog-service
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8082
env:
  - name: CATALOG_DB_HOST
    value: "postgres-catalog"
  - name: CATALOG_DB_USER
    value: "catalog_user"
  - name: CATALOG_DB_PASSWORD
    value: "catalog_pass"
  - name: CATALOG_DB_NAME
    value: "catalog_db"
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
